USE Matrix;

ALTER TABLE dbo.TELEPHONE
ADD NIUMERO VARCHAR(8)

ALTER TABLE dbo.GROUPE
ADD NOM VARCHAR(50);

ALTER TABLE dbo.LIEU
ADD IDTYP int;

ALTER TABLE dbo.LIEU
ADD CONSTRAINT FK_LIEU_TYPE
FOREIGN KEY (IDTYP) REFERENCES dbo.TYP(IDTYP);

ALTER TABLE dbo.LIEU
ADD IDROL int;

ALTER TABLE dbo.LIEU
ADD CONSTRAINT FK_LIEU_ROLE
FOREIGN KEY (IDROL) REFERENCES dbo.ROL(IDROL);


CREATE TABLE dbo.JOUEUR
(
IDJOUEUR int identity(0, 1) not null,
NOM varchar(50) not null,
PSEUDO varchar(50) UNIQUE not null,
PASSWORD varchar(15) not null,
constraint PK_JOUEUR primary key(IDJOUEUR)
);

CREATE TABLE dbo.ENNEMI
(
IDENNEMI int identity(0, 1) not null,
NOM varchar(50),
LIFEPOINT int,
constraint PK_ENNEMI primary key (IDENNEMI));


CREATE TABLE dbo.TYPENEMI
(
IDTYPENEMI int identity(0, 1) not null,
NOM varchar(50) UNIQUE not null,
constraint PK_TYPENEMI primary key (IDTYPENEMI));

CREATE TABLE dbo.SESSIONJEU
(
IDSESSION int identity(0, 1) not null,
STARTIME  DATETIME,
ENDTIME  DATETIME,
constraint PK_SESSIONJEU primary key (IDSESSION));

CREATE TABLE dbo.PARTIE
(
IDPARTIE int identity(0, 1) not null,
STARTIME  DATETIME,
ENDTIME  DATETIME,
SCORE int,
constraint PK_PARTIE primary key (IDPARTIE)
);

CREATE TABLE dbo.CONTROLER
(
IDCONTROLE int identity(0, 1) not null,
constraint PK_CONTROLER primary key (IDCONTROLE)
);

ALTER TABLE dbo.CONTROLER
ADD IDTEL int;

ALTER TABLE dbo.CONTROLER
ADD CONSTRAINT FK_CONTROLER_TELEPHONE
FOREIGN KEY (IDTEL) REFERENCES dbo.TELEPHONE(IDTEL);

ALTER TABLE dbo.CONTROLER
ADD IDENNEMI int;

ALTER TABLE dbo.CONTROLER
ADD CONSTRAINT FK_CONTROLER_ENNEMI
FOREIGN KEY (IDENNEMI) REFERENCES dbo.ENNEMI(IDENNEMI);


CREATE TABLE dbo.ELIMINER
(
IDELIMINE int identity(0, 1) not null,
constraint PK_ELIMINER primary key (IDELIMINE)
);

ALTER TABLE dbo.ELIMINER
ADD IDPERS int;

ALTER TABLE dbo.ELIMINER
ADD CONSTRAINT FK_ELIMINER_PERSONNAGE
FOREIGN KEY (IDPERS) REFERENCES dbo.PERSONNAGE(IDPERS);

ALTER TABLE dbo.ELIMINER
ADD IDENNEMI int;

ALTER TABLE dbo.ELIMINER
ADD CONSTRAINT FK_ELIMINER_ENNEMI
FOREIGN KEY (IDENNEMI) REFERENCES dbo.ENNEMI(IDENNEMI);


CREATE TABLE dbo.CREER
(
IDCREE int identity(0, 1) not null,
constraint PK_CREER primary key (IDCREE)
);

ALTER TABLE dbo.CREER
ADD IDJOUEUR int;

ALTER TABLE dbo.CREER
ADD CONSTRAINT FK_CREER_JOUEUR
FOREIGN KEY (IDJOUEUR) REFERENCES dbo.JOUEUR(IDJOUEUR);

ALTER TABLE dbo.CREER
ADD IDSESSION int;

ALTER TABLE dbo.CREER
ADD CONSTRAINT FK_CREER_SESSIONJEU
FOREIGN KEY (IDSESSION) REFERENCES dbo.SESSIONJEU(IDSESSION);

ALTER TABLE dbo.CREER
ADD IDJOUEUR int;

ALTER TABLE dbo.CREER
ADD CONSTRAINT FK_CREER_JOUEUR
FOREIGN KEY (IDJOUEUR) REFERENCES dbo.JOUEUR(IDJOUEUR);

ALTER TABLE dbo.PARTIE
ADD IDSESSION int;

ALTER TABLE dbo.PARTIE
ADD CONSTRAINT FK_PARTIE_SESSIONJEU
FOREIGN KEY (IDSESSION) REFERENCES dbo.SESSIONJEU(IDSESSION);

ALTER TABLE dbo.ENNEMI
ADD IDTYPENEMI int;

ALTER TABLE dbo.ENNEMI
ADD CONSTRAINT FK_ENNEMI_TYPENEMI
FOREIGN KEY (IDTYPENEMI) REFERENCES dbo.TYPENEMI(IDTYPENEMI);

ALTER TABLE dbo.PERSONNAGE
ADD IDJOUEUR int;

ALTER TABLE dbo.PERSONNAGE
ADD CONSTRAINT FK_PERSONNAGE_JOUEUR
FOREIGN KEY (IDJOUEUR) REFERENCES dbo.JOUEUR(IDJOUEUR);



