USE Matrix;

INSERT INTO PERSONNAGE VALUES ('Zeya', 50, 2, 1, 1);
INSERT INTO PERSONNAGE VALUES ('Optimus', 100, 1, 1, 2);

INSERT INTO TYPENEMI VALUES ('Boot');
INSERT INTO TYPENEMI VALUES ('Boss');

INSERT INTO ENNEMI VALUES ('Agent', 150, 1);
INSERT INTO ENNEMI VALUES ('Agent1', 150, 1);
INSERT INTO ENNEMI VALUES ('Smith', 500, 2);

INSERT INTO JOUEUR VALUES ('Morphéus', 'Kran23', 'passtest1');
INSERT INTO JOUEUR VALUES ('Néo', 'TCH666', 'oday203');

INSERT INTO ELIMINER VALUES (1, 1);
INSERT INTO ELIMINER VALUES (2, 2);
INSERT INTO ELIMINER VALUES (1, 2);
INSERT INTO ELIMINER VALUES (2, 1);


INSERT INTO SESSIONJEU VALUES ('2020-06-06 09:00', '2020-06-09 11:00');
INSERT INTO SESSIONJEU VALUES ('2020-07-07 09:00', '2020-06-09 11:00');

INSERT INTO PARTIE VALUES ('2020-06-06 09:00', '2020-06-09 11:00', 100, 2);
INSERT INTO PARTIE VALUES ('2020-06-06 09:00', '2020-06-09 11:00', 90, 1);
INSERT INTO PARTIE VALUES ('2020-06-06 23:00', '2020-06-09 23:30', 50, 1);

INSERT INTO CREER VALUES (1, 1);
INSERT INTO CREER VALUES (2, 2);


INSERT INTO GROUPE VALUES ('', 'fictif');
INSERT INTO GROUPE VALUES ('', 'réel');

INSERT INTO CATEGORIE VALUES ('Armurie');
INSERT INTO CATEGORIE VALUES ('Chapeau');

INSERT INTO CARACTERISTIQUE VALUES ('Armure du roi Arthur', 1);
INSERT INTO CARACTERISTIQUE VALUES ('Cape magique', 1);

INSERT INTO POSSEDER VALUES (1, 1);
INSERT INTO POSSEDER VALUES (1, 2);

INSERT INTO TYP VALUES ('salle');
INSERT INTO TYP VALUES ('rue');
INSERT INTO TYP VALUES ('ville détruite');


INSERT INTO ROL VALUES ('entrainement combat');
INSERT INTO ROL VALUES ('combat');
INSERT INTO ROL VALUES ('vendetta');

INSERT INTO CATEGORIE_ARME VALUES ('M10 rafale', 45);
INSERT INTO CATEGORIE_ARME VALUES ('Explosif', 5);

INSERT INTO ARME VALUES ('Ak47', 'mitraillette', 1);
INSERT INTO ARME VALUES ('Lance-grenade', 'portée de 100m', 2);

INSERT INTO LIEU VALUES (20, 10, 5, 'Cité perdue', 'grande bataille', 3, 3);
INSERT INTO LIEU VALUES (1, 1, 1, 'entraînement boot', 'salle entraînement', 1, 1);


INSERT INTO APPARAITRE VALUES (1, 1);
INSERT INTO APPARAITRE VALUES (2, 1);
INSERT INTO APPARAITRE VALUES (1, 2);

INSERT INTO TELEPHONE VALUES (0, '5945553');
INSERT INTO TELEPHONE VALUES (1, '5940663');

INSERT INTO PLACER VALUES (1, 1);
INSERT INTO PLACER VALUES (2, 1);

INSERT INTO APPARAITRE VALUES (1, 1);

